### ISSUE TITLE
ReferenceError after the compatibility check

### ISSUE THREAD

**Issue by ncoden** [mozesmagyar/gulp-browser-compat#1]
I got the following error after the compatibility check:
```log
/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:132
				if (typeof browserConf.fail !== 'undefined' && (browserConf.report === versionRange[0] || browserConf.fail !== versionHigher([versionRange[0], conf[a].fail]))) {
				                                                                                                                                                    ^

ReferenceError: a is not defined
    at closure (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:132:153)
    at Array.reduce (native)
    at closure (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:184:52)
    at Array.reduce (native)
    at closure (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:203:45)
    at Array.reduce (native)
    at compat (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:262:25)
    at parseCompatFiles (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:444:9)
    at Request._callback (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:484:5)
    at Request.self.callback (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/node_modules/request/request.js:200:22)
```

You can see the full log here : https://gist.github.com/ncoden/ea3e555f023e13112b9ff1e01f1765d2

Is this project still maintained ? If not, do you know an equivalent package ?

**Comment by arroo** [comment]
This has been fixed.
The project will probably be as maintained issues come in.
There is no inherently equivalent package, which is why I wrote it.

**Comment by ncoden** [comment]
@mozesmagyar Thanks
