### ISSUE TITLE
no such file or directory: additional.json

### ISSUE THREAD

**Issue by ncoden** [mozesmagyar/gulp-browser-compat#3]
I have the following error after a fresh install.
```shell
➜  foundation-sites git:(chore/browser-compat) ✗ gulp lint:browserCompatibility
[23:34:56] Using gulpfile ~/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/gulpfile.js
[23:34:56] Starting 'lint:browserCompatibility'...
[23:34:57] Finished 'lint:browserCompatibility' after 1.39 s
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/gulp-browser-compat/additional.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:386:34
    at Array.map (native)
    at parseCompatFiles (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:372:16)
    at Request._callback (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/index.js:484:5)
    at Request.self.callback (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/Forks/foundation-sites/node_modules/gulp-browser-compat/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
```

The package directory is:
```shell
➜  foundation-sites git:(chore/browser-compat) ✗ la node_modules/gulp-browser-compat
total 2576
-rw-r--r--  1 ncoden  admin   1.3K Jun 22 20:25 LICENCE
-rw-r--r--  1 ncoden  admin   2.0K Jun 22 20:26 README.md
-rw-r--r--  1 ncoden  admin    15B Nov 15 23:35 additional.json.new
-rw-r--r--  1 ncoden  admin    15B Nov 15 23:35 caniuse2.json.new
-rw-r--r--  1 ncoden  admin   1.2M Nov 15 23:35 data.json.new
-rw-r--r--  1 ncoden  admin    14K Nov 15 15:43 index.js
drwxr-xr-x  5 ncoden  admin   170B Nov 15 23:34 node_modules
-rw-r--r--  1 ncoden  admin   1.7K Nov 15 23:34 package.json
-rw-r--r--  1 ncoden  admin   7.4K Jun 22 20:25 rules.js
```

**Comment by arroo** [comment]
closed fixed by recent merge
